/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AppFooter: typeof import('./components/AppFooter.vue')['default']
    FeatureCard: typeof import('./components/FeatureCard.vue')['default']
    FeaturesGrid: typeof import('./components/FeaturesGrid.vue')['default']
    FeaturesSection: typeof import('./components/FeaturesSection.vue')['default']
    HelloWorld: typeof import('./components/HelloWorld.vue')['default']
    HeroSection: typeof import('./components/HeroSection.vue')['default']
    MainLayout: typeof import('./components/MainLayout.vue')['default']
    MovieCard: typeof import('./components/MovieCard.vue')['default']
    MovieDetail: typeof import('./components/MovieDetail.vue')['default']
    Movies: typeof import('./components/Movies.vue')['default']
    Navbar: typeof import('./components/Navbar.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SearchResults: typeof import('./components/SearchResults.vue')['default']
    TVShowsCard: typeof import('./components/TVShowsCard.vue')['default']
  }
}
